# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Songlin Zhao
title: Undergraduate student at The Chinese University of Hong Kong, Shenzhen
email: 120090346@link.cuhk.edu.cn
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  thiefCat
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: Songlin Zhao
# flickr_username: jekyll
instagram_username: thief_cat7918
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am a junior undergraduate student at The Chinese University of Hong Kong, Shenzhen. My major is Data Science and Big Data Technology. 
  I am interested in computer vision, computational photography and graph theory. 

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: The Chinese Uniersity of Hong Kong, Shenzhen
        caption: Expected graduation June 2024
        sub_title: BSc Data Science and Big Data Technology
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I major in Data Science and Big Data Technology at CUHKSZ. Important courses: Machine Learning, Numerical Methods, Stochastic Process,
          Optimization, Digital Image Processing and Computer Vision.

          My honors & rewards are as follows:
          - Dean's List, 2020-2021
          - Academic Performance Scholarship: class B, 2020-2021
          - Dean's List, 2021-2022
          - Academic Performance Scholarship: class B, 2021-2022
        

      - layout: top
        title: University of California, Berkeley
        sub_title: January 2023 - March 2023
        caption: Visiting student
        description: | # this will include new lines to allow paragraphs
          Majoring in Computer Science, I learned Algorithm, Deep Learning, and Data Structure at UC Berkeley.
          
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Computer vision project of video stitching and deblurring
        link: github.com/thiefCat/thiefCat.github.io/blob/main/reports/video_stitching_report.pdf
        link_text: Link to Report
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/thiefCat/EIE4512_pano_proj
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          -	Realized image stitching to obtain a panorama using algorithms SIFT detector and Homography
          -	Achieved cylindrical projection of a set of images
          -	Estimated the motion of the camera by the vedeo and then deblurred the panorama
      
      - layout: top
        title: Computer vision project of segmentation and image inpainting
        link: github.com/thiefCat/thiefCat.github.io/blob/main/reports/image_inpainting_report.pdf
        link_text: Link to Report
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/orgs/ECE-Img-Inpainting/repositories
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          -	Realized interactively image segmentation algorithm using graph cut
          -	Achieved Exemplar-based image inpainting and scene matching image inpainting algorithm
        
      - layout: top
        title: Numerical Analysis project on singular value decomposition and QR iteration
        link: github.com/thiefCat/thiefCat.github.io/blob/main/reports/SVD_report.pdf
        link_text: Link to Report
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: github.com/Linnore/DDA3005_114514
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - Implemented a two-phase method to perform SVD
          - Performed SVD to solve image deblurring problem
          -	Performed SVD and QR iteration to solve video background extraction problem


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: The Chinese Uniersity of Hong Kong, Shenzhen
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 
          Undergraduate Student Teaching Fellow
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I works as teaching assistant for two courses:
          - Computational Laboratory, Spring 2022
          - Discrete Mathematics, Fall 2022


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
